{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cipherstash-proxy.fullname" . }}-secrets
  namespace: {{ include "cipherstash-proxy.namespace" . }}
  labels:
    {{- include "cipherstash-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $databasePassword := .Values.secrets.databasePassword | default .Values.database.password }}
  {{- if $databasePassword }}
  database-password: {{ $databasePassword | b64enc | quote }}
  {{- else }}
  {{- fail "database password is required when secrets.create is true. Provide either secrets.databasePassword or database.password" }}
  {{- end }}
  {{- $cipherstashClientKey := .Values.secrets.cipherstashClientKey | default .Values.cipherstash.clientKey }}
  {{- if $cipherstashClientKey }}
  cipherstash-client-key: {{ $cipherstashClientKey | b64enc | quote }}
  {{- else }}
  {{- fail "CipherStash client key is required when secrets.create is true. Provide either secrets.cipherstashClientKey or cipherstash.clientKey" }}
  {{- end }}
  {{- $cipherstashClientAccessKey := .Values.secrets.cipherstashClientAccessKey | default .Values.cipherstash.clientAccessKey }}
  {{- if $cipherstashClientAccessKey }}
  cipherstash-client-access-key: {{ $cipherstashClientAccessKey | b64enc | quote }}
  {{- else }}
  {{- fail "CipherStash client access key is required when secrets.create is true. Provide either secrets.cipherstashClientAccessKey or cipherstash.clientAccessKey" }}
  {{- end }}
{{- end }}
