name: Setup Rust

runs:
  using: composite
  steps:

    - name: Install
      shell: /bin/bash -l {0}
      run: rustup toolchain install stable --profile minimal --no-self-update

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
