[package]
name = "eql-mapper-macros"
description = "Macros to reduce boilerplate in the implementation of eql-mapper"
version.workspace = true
edition.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
pretty_assertions = "1.4.1"
