# Configuration for chart-testing
# See https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md

# The name of the target branch used to identify changed charts.
target-branch: main

# The directories containing charts
chart-dirs:
  - charts

# Charts to exclude from testing (use chart name)
excluded-charts: []

# Validate maintainers in Chart.yaml
validate-maintainers: true

# Disable chart version checking (handled by automated release process)
check-version-increment: false

# Enable linting of Chart.yaml schema
validate-chart-schema: true

# Enable linting of values.yaml schema
validate-yaml-schema: true

# Additional Helm repositories to add before linting/testing
helm-repos:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

# Additional values files to use for installation tests
additional-values-files: []

# Debug output
debug: false
