[vars]
database_port = "5532" # default postgres port using built in docker-compose setup

[env]
CS_DATABASE__PORT = "5532"
PKG_CONFIG_PATH = "/opt/homebrew/opt/icu4c@76/lib/pkgconfig"

[tools]
"cargo:cargo-binstall" = "latest"
"cargo:cargo-expand" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-sort" = "latest"

[tasks.proxy]
alias = 'p'
description = "Runs the proxy "
run = 'cargo run'

# ====================================================================================================
# Test Tasks

[tasks.test]
alias = 't'
description = "Runs test/s"
run = """
  mise run test:nextest {{arg(name="test",default="")}}
  mise run test:check
  mise run test:format
  mise run test:clippy
"""

[tasks."test:nextest"]
description = "Runs cargo nextest"
run = 'cargo nextest run --no-fail-fast --nocapture {{arg(name="test",default="")}}'

[tasks."test:format"]
description = "Runs cargo fmt"
run = 'cargo fmt --all -- --check'

[tasks."test:check"]
description = "Runs cargo check"
run = 'cargo check'

[tasks."test:clippy"]
description = "Runs clippy"
run = 'cargo clippy --all --no-deps --all-targets --all-features'

[tasks.setup]
depends = ["install_eql"]
alias = 's'
description = "Installs EQL and applies schema to database"
dir = "./tests"
run = "cat sql/schema.sql | docker exec -i postgres psql postgresql://cipherstash:password@localhost:{{vars.database_port}}/cipherstash -f-"

[tasks.up]
alias = 'u'
dir = "./tests"
description = "docker compose up"
run = """
chmod 600 tls/*
if [ -n "$CI" ]; then echo "Running in CI: setting file permissions for container" ; sudo chown 999:999 tls/localhost* ; else echo "Not running in CI: skip setting file permissions for container" ; fi
docker compose up --build {{arg(name="service",default="")}} {{option(name="extra-args",default="")}}
"""

[tasks.down]
alias = 'd'
description = 'Tear down containers and destroy all data'
run = """
  mise run compose_down
  mise run destroy_data
"""

[tasks.compose_down]
dir = "./tests"
description = "docker compose down"
run = 'docker compose down'

[tasks.destroy_data]
alias = 'dd'
dir = "./tests/pg"
description = "Removes the local data directories"
run = 'rm -rf data-*'

[tasks.install_eql]
alias = 'e'
description = "Install EQL"
dir = "./tests"
run = """
  #!/usr/bin/env bash
  curl -sLo sql/cipherstash-encrypt.sql https://github.com/cipherstash/encrypt-query-language/releases/latest/download/cipherstash-encrypt.sql
  cat sql/cipherstash-encrypt.sql | docker exec -i postgres psql postgresql://cipherstash:password@localhost:{{vars.database_port}}/cipherstash -f-
"""

[tasks.release]
description = "Build a releasable binary"
run = """
cargo build --locked --release --package cipherstash-proxy
cp -v target/release/cipherstash-proxy .
"""

# ====================================================================================================
