


[tasks.test]
alias = 't'
description = "All test"
# run = 'cargo nextest run --no-fail-fast --nocapture {{arg(name="test",default="")}}'
run = """
#!/usr/bin/env bash
psql postgresql://mlp:password@localhost:5532/mlp < tests/sql/schema.sql
cargo nextest run --no-fail-fast --nocapture {{arg(name="test",default="")}}
"""

[tasks.up]
alias = 'u'
dir = "./tests"
description = "docker compose up"
run = 'docker compose up --build {{arg(name="service",default="")}}'

[tasks.install_eql]
alias = 'e'
description = "Install EQL"
run = """
#!/usr/bin/env bash
curl -sLo tests/sql/cipherstash-encrypt.sql https://github.com/cipherstash/encrypt-query-language/releases/latest/download/cipherstash-encrypt.sql
psql postgresql://mlp:password@localhost:5532/mlp < tests/sql/cipherstash-encrypt.sql
"""
