


[tasks.test]
alias = 't'
description = "All test"
run = 'cargo nextest run --no-fail-fast --nocapture {{arg(name="test",default="")}}'


[tasks.up]
alias = 'u'
dir = "./tests"
description = "docker compose up"
run = 'docker compose up --build {{arg(name="service",default="")}}'
