[settings]
# Config for test environments
# Can be invoked with: mise --env tcp run <task>
trusted_config_paths = [
  "./tests/mise.toml",
  "./tests/mise.tcp.toml",
  "./tests/mise.tls.toml",
]

[task_config]
includes = ["tests/tasks"]

[vars]
database_port = "5532" # default postgres port using built in docker-compose setup

[env]
# Default configuration for running cipherstash-proxy out of the box
CS_DATABASE__NAME = "cipherstash"
CS_DATABASE__USERNAME = "cipherstash"
CS_DATABASE__PASSWORD = "password"
CS_DATABASE__HOST = "localhost"
CS_DATABASE__PORT = "5532"

[tools]
"cargo:cargo-binstall" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-sort" = "latest"

[tasks.proxy]
alias = 'p'
description = "Runs the proxy"
run = 'pwd && env | grep CS_ && cargo run'

[tasks.kill]
alias = 'k'
description = "Kills running proxy "
run = """
  killall cipherstash-proxy -s SIGINT
  exit 0
"""

# ====================================================================================================
# Test Tasks

[tasks."test:unit"]
alias = ['t', 'test']
description = "Runs tests"
run = "mise run test:nextest {{arg(name='test',default='')}}"

[tasks."test:ci"]
alias = "ci"
description = "Runs test/s"
run = """
  mise run test:check
  mise run test:format
  mise run test:clippy
  mise run test:unit
  mise run test:integration
"""

[tasks."test:wait_for_tcp_port"]
run = """
{% set default_host = get_env(name="CS_DATABASE__HOST",default="localhost") %}
{% set default_port = get_env(name="CS_DATABASE__PORT",default=5432) %}
  host={{option(name="host",default=default_host)}}
  port={{option(name="port",default=default_port)}}
  max_retries=10
  attempt=1
  until nc -z $host $port
  do
    if [ $attempt -lt $max_retries ]; then
      echo "Waiting for ${host}:${port}"
      sleep 0.5
      attempt=$(expr $attempt + 1)
    else
      echo "Unable to connect to ${host}:${port} after ${max_retries} attempts"
      exit 64
    fi
  done
  echo "Connected to ${host}:${port} after ${attempt} attempts"
"""

[tasks."test:integration"]
alias = "i"
dir = "./tests"
description = "Runs integration test/s"
run = """
  mise --env tcp run proxy &
  mise --env tcp run test:wait_for_tcp_port --port 6432
  mise --env tcp run test:psql-tcp
  mise run kill

  # mise --env tls run proxy &
  # mise --env tls run test:wait_for_tcp_port --port 6432
  # mise --env tls run test:psql-tls
  # mise run kill

  # mise --env tls run proxy &
  # mise --env tls run test:wait_for_tcp_port --port 6432
  # cargo nextest run --no-fail-fast --nocapture -E 'test(~integration)'
  # mise run kill
"""

[tasks."test:nextest"]
description = "Runs cargo nextest, skipping integration tests"
run = 'cargo nextest run --no-fail-fast --nocapture -E "not test(~integration)" {{arg(name="test",default="")}}'

[tasks."test:format"]
description = "Runs cargo fmt"
run = 'cargo fmt --all -- --check'

[tasks."test:check"]
description = "Runs cargo check"
run = 'cargo check'

[tasks."test:clippy"]
description = "Runs clippy"
run = 'cargo clippy --all --no-deps --all-targets --all-features'

[tasks.setup]
depends = ["install_eql"]
alias = 's'
description = "Installs EQL and applies schema to database"
run = """
  #!/bin/bash
  cd tests
  cat sql/schema.sql | docker exec -i postgres${CONTAINER_SUFFIX} psql postgresql://${CS_DATABASE__USERNAME}:${CS_DATABASE__PASSWORD}@${CS_DATABASE__HOST}:${CS_DATABASE__PORT}/cipherstash -f-
"""

[tasks."postgres:up"]
alias = 'u'
dir = "./tests"
description = "docker compose up"
run = """
chmod 600 tls/*
if [ -n "$CI" ]; then echo "Running in CI: setting file permissions for container" ; sudo chown 999:999 tls/localhost* ; else echo "Not running in CI: skip setting file permissions for container" ; fi
echo docker compose up --build {{arg(name="service",default="")}} {{option(name="extra-args",default="")}} | bash
"""

[tasks."postgres:down"]
alias = 'd'
description = 'Tear down containers and destroy all data'
run = """
  mise run postgres:compose_down
  mise run postgres:destroy_data
"""

[tasks."postgres:compose_down"]
dir = "./tests"
description = "docker compose down"
run = 'docker compose down'

[tasks."postgres:destroy_data"]
alias = 'dd'
dir = "./tests/pg"
description = "Removes the local data directories"
run = 'rm -rf data-*'

[tasks.install_eql]
alias = 'e'
description = "Install EQL"
run = """
  #!/usr/bin/env bash
  cd tests
  curl -sLo sql/cipherstash-encrypt.sql https://github.com/cipherstash/encrypt-query-language/releases/latest/download/cipherstash-encrypt.sql
  cat sql/cipherstash-encrypt.sql | docker exec -i postgres${CONTAINER_SUFFIX} psql postgresql://${CS_DATABASE__USERNAME}:${CS_DATABASE__PASSWORD}@${CS_DATABASE__HOST}:${CS_DATABASE__PORT}/cipherstash -f-
"""

[tasks.build]
description = "Build releasable artifacts"
run = """
{% set default_platform = "linux/" ~ arch() | replace(from="x86_64", to="amd64") %}
mise run build:binary
mise run build:docker --platform {{option(name="platform",default=default_platform)}} \
"""

[tasks."build:binary"]
description = "Build a releasable binary for cipherstash-proxy"
run = """
cargo build --locked --release --package cipherstash-proxy
cp -v target/release/cipherstash-proxy .
"""

[tasks."build:docker"]
depends = ["build:docker:fetch_eql"]
description = "Build a Docker image for cipherstash-proxy"
run = """
{% set default_platform = "linux/" ~ arch() | replace(from="x86_64", to="amd64") %}
docker build . \
  --tag cipherstash/proxy:latest \
  --file proxy.Dockerfile \
  --platform {{option(name="platform",default=default_platform)}} \
"""

[tasks."build:docker:fetch_eql"]
description = "Fetch the EQL installation script"
run = """
if [ ! -e "cipherstash-eql.sql" ]; then
  echo "Fetching: cipherstash-eql.sql"
  curl -sLo cipherstash-eql.sql https://github.com/cipherstash/encrypt-query-language/releases/latest/download/cipherstash-encrypt.sql
else
  echo "Prefetched: cipherstash-eql.sql"
fi
"""

[tasks.release]
description = "Publish release artifacts"
depends = ["release:docker"]

[tasks."release:docker"]
description = "Release a Docker image for cipherstash-proxy"
run = """
if [ -z "$DOCKER_HUB_USERNAME" ] || [ -z "$DOCKER_HUB_PERSONAL_ACCESS_TOKEN" ]; then
  echo "error: no Docker Hub credentials provided"
  echo "error: please set DOCKER_HUB_USERNAME and DOCKER_HUB_PERSONAL_ACCESS_TOKEN"
  exit 2
fi
echo "Logging in to Docker Hub..."
echo $DOCKER_HUB_PERSONAL_ACCESS_TOKEN | docker login --username $DOCKER_HUB_USERNAME --password-stdin
docker tag cipherstash/proxy:latest cipherstash/proxy:latest
docker push cipherstash/proxy:latest
"""

# ====================================================================================================
