[package]
name = "eql-mapper"
description = "The SQL transformation layer of CipherStash Proxy. Safely transforms SQL to SQL+EQL using a reference schema and type inference approach"
version = "0.1.0"
edition = "2021"
authors = [
  "James Sadler <james@cipherstash.com>",
  "Yuji Yokoo <yuji@cipherstash.com>",
  "Ragib Badaruddin <ragib@cipherstash.com>",
]

[dependencies]

cipherstash-client = { git = "ssh://git@github.com/cipherstash/cipherstash-suite.git", branch = "main" }
cipherstash-config = { git = "ssh://git@github.com/cipherstash/cipherstash-suite.git", branch = "main" }
derive_more = { version = "1", features = ["full"] }
sqlparser = { version = "0.52.0", features = ["bigdecimal"] }
sqltk = { git = "ssh://git@github.com/cipherstash/sqltk.git", branch = "main" }
thiserror = "2.0.3"

[dev-dependencies]
pretty_assertions = "1.4.1"
