[package]
name = "eql-mapper"
description = "The SQL transformation layer of CipherStash Proxy. Safely transforms SQL to SQL+EQL using a reference schema and type inference approach"
version = "0.1.0"
edition = "2021"
authors = [
  "James Sadler <james@cipherstash.com>",
  "Yuji Yokoo <yuji@cipherstash.com>",
  "Ragib Badaruddin <ragib@cipherstash.com>",
]

[dependencies]
cipherstash-client = { git = "ssh://git@github.com/cipherstash/cipherstash-suite.git", branch = "main" }
cipherstash-config = { git = "ssh://git@github.com/cipherstash/cipherstash-suite.git", branch = "main" }
derive_more = { version = "^1.0", features = ["display", "constructor"] }
itertools = "^0.13"
sqlparser = { workspace = true }
sqltk = { git = "https://github.com/cipherstash/sqltk/", branch = "CIP-1079/update-sqlparser" }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
pretty_assertions = "^1.0"

[profile.dev]
incremental = true
debug = true
