[package]
name = "cipherstash-proxy-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
cipherstash-proxy = { path = "../cipherstash-proxy/" }
chrono = { version = "0.4.39", features = ["clock"] }
rand = "0.8.5"
recipher = "0.1.3"
temp-env = "0.3.6"
tokio = { version = "1.42.0", features = ["full"] }
tokio-postgres = { version = "0.7", features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
tokio-postgres-rustls = "0.13.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
