[package]
name = "cipherstash-proxy-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
cipherstash-proxy = { path = "../cipherstash-proxy/" }
chrono = { version = "0.4.39", features = ["clock"] }
rand = "0.9"
recipher = "0.1.3"
rustls = { version = "0.23.20", default-features = false, features = ["std"] }
serde = "1.0"
serde_json = "1.0"
temp-env = "0.3.6"
tokio = { workspace = true }
tokio-postgres = { version = "0.7", features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
tokio-postgres-rustls = "0.13.0"
tokio-rustls = "0.26.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
webpki-roots = "0.26.7"

[dev-dependencies]
# cipherstash-client = { version = "0.18.0-pre.1", features = ["tokio"] }
cipherstash-client = { path = "../../../cipherstash-suite/packages/cipherstash-client", features = [
    "tokio",
] }
# cipherstash-config = "0.2.3"
cipherstash-config = { path = "../../../cipherstash-suite/packages/cipherstash-config" }
clap = "4.5.32"
fake = { version = "4", features = ["chrono", "derive"] }
hex = "0.4.3"
uuid = { version = "1.11.0", features = ["serde", "v4"] }
