# Test values for chart-testing CI
# 
# NOTE: This file will be automatically overwritten during CI runs
# with values from GitHub secrets. The template is in test-values.yaml.template
#
# These values provide minimal configuration for testing chart installation

database:
  host: "postgres.example.com"
  name: "testdb"
  port: "5432"
  username: "testuser"
  password: "testpass"

cipherstash:
  workspaceCrn: "crn:region:id"
  clientId: "test-client-id"
  clientKey: "test-client-key"
  clientAccessKey: "test-client-access-key"

# Disable secrets for testing to use plain text values
secrets:
  create: false

# Minimal resources for testing
resources:
  limits:
    cpu: 200m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 256Mi

# Disable metrics service for simpler testing
metricsService:
  enabled: false

# Disable prometheus for testing
prometheus:
  enabled: false

# Use minimal probes for faster testing
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
  readiness:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
