name: Setup Test
description: |
  This action sets up the environment for running tests in a Rust project.
  It installs Rust, sets up caching, and installs mise.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Install rust
      shell: /bin/bash -l {0}
      run: rustup toolchain install stable --profile minimal --no-self-update
    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-provider: ${{ inputs.provider }}
        shared-key: ${{ inputs.key }}
        cache-all-crates: true
    - uses: jdx/mise-action@v2
      with:
        version: 2025.1.0 # [default: latest] mise version to install
        install: true # [default: true] run `mise install`
        cache: true # [default: true] cache mise using GitHub's cache

