[package]
name = "cipherstash-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = { version = "0.4.6", features = ["serde-json"] }
arc-swap = "1.7.1"
bytes = { version = "1.9", default-features = false }
chrono = { version = "0.4.39", features = ["clock"] }
cipherstash-client = { version = "0.16", features = ["tokio"] }
cipherstash-config = "0.2.3"
config = { version = "0.15", features = [
    "async",
    "convert-case",
    "json",
    "toml",
], default-features = false }
eql-mapper = { path = "../eql-mapper" }
exitcode = "1.1.2"
hex = "0.4.3"
itertools = "0.14.0"
md-5 = "0.10.6"
native-tls = "0.2.12"
oid-registry = "0.8"
pg_escape = "0.1.1"
postgres-protocol = "0.6.7"
postgres-types = { version = "0.2.8", features = [] }
rand = "0.9"
regex = "1.11.1"
ring = { version = "0.17", default-features = false }
rust_decimal = { version = "1.36.0", default-features = false, features = [
    "db-postgres",
] }
rustls = { version = "0.23.20", default-features = false, features = ["std"] }
rustls-pki-types = "1.10.0"
serde = "1.0"
serde_json = "1.0"
socket2 = "0.5.7"
sqlparser = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.42.0", features = ["full"] }
tokio-postgres = { version = "0.7", features = [
    "with-chrono-0_4",
    "with-serde_json-1",
] }
tokio-postgres-rustls = "0.13.0"
tokio-rustls = "0.26.0"
tokio-util = { version = "0.7.13", features = ["rt"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { version = "1.11.0", features = ["serde", "v4", "v5"] }
webpki-roots = "0.26.7"
x509-parser = "0.17.0"

[dev-dependencies]
recipher = "0.1.3"
temp-env = "0.3.6"
