name: "Test Rust"
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**

  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**

  workflow_call:

defaults:
  run:
    shell: /bin/bash -l {0}

env:
  RUSTFLAGS: "-D warnings"
  RUST_BACKTRACE: full
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust

      - name: format
        run: cargo fmt --all -- --check

      - name: check
        run: cargo check

      - name: clippy
        run: cargo clippy --all --no-deps --all-targets --all-features

